### ISSUE TITLE
How I can run your kindlechess2 app?

### ISSUE THREAD

**Issue by la-morsa** [pbbwfc/KindleChess#1]
I am not a F# programmer and in fact, I dont use Visual Studio for my programming chores. I am a chess player and writer and I would like to build chess books for Kindle. I followed your instructions but the kindlechess2.exe does not do anything at all? Am I doing something wrong? Do I have to unzip in a specific directory? Sorry to bother you.
Regards
Manuel

**Comment by pbbwfc** [comment]
Sorry about this.

The version compiled in the zip only runs on Windows 10 64 bit and you need NET Core 3.1 also installed.

You can get this for example from:
https://download.visualstudio.microsoft.com/download/pr/5954c748-86a1-4823-9e7d-d35f6039317a/169e82cbf6fdeb678c5558c5d0a83834/windowsdesktop-runtime-3.1.3-win-x64.exe

I should also say that although I have used this version to create Chess Books I am now using another version which is significantly different in that it uses PGN files to store the data. This makes it easier to understand how it works and to tweak it (if necessary) by manually editing the PGN files. Although manual tweaking this should not be necessary in the longer term as I update the code!

I have now put this updated version on Github - see
https://github.com/pbbwfc/KindleChess3
